version: '3'

services:
  client:
    container_name: realtime-quiz-client
    image: realtime-quiz-client:1.0.0
    build:
      context: client
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - '8080:8080'
    networks:
      - realtime-quiz-app
    depends_on:
      - api

  api:
    container_name: realtime-quiz-api
    image: realtime-quiz-api:1.0.0
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - realtime-quiz-app
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - '27017:27017'
    networks:
      - realtime-quiz-app
    volumes:
      - mongo-data:/data/db

networks:
  realtime-quiz-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
