const USER_ROLES = {
	ADMIN: 'ADMIN',
	CLIENT: 'CLIENT',
};

const QUIZ_STATUSES = {
	ACTIVE: 'ACTIVE',
	DELETED: 'DELETED',
};

const SESSION_STATUSES = {
	ACTIVE: 'ACTIVE',
	EXPIRED: 'EXPIRED',
};

module.exports = { USER_ROLES, QUIZ_STATUSES, SESSION_STATUSES };
